# Generated by Django 4.2.7 on 2025-11-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, help_text="Name of the object category (e.g., 'car', 'person')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the object category')),
                ('icon', models.ImageField(blank=True, help_text='Icon representing this category', null=True, upload_to='object_icons/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this category is available for training/detection')),
                ('training_images_count', models.IntegerField(default=0, help_text='Total number of training images for this category')),
                ('detection_count', models.IntegerField(default=0, help_text='Total number of detections made')),
                ('created_by', models.ForeignKey(help_text='User who created this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object Category',
                'verbose_name_plural': 'Object Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='objects_obj_name_5ddda4_idx')],
            },
        ),
    ]
