# Generated by Django 4.2.7 on 2025-11-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the device', unique=True)),
                ('name', models.CharField(help_text='Human-readable name for the device', max_length=200)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile Device'), ('desktop', 'Desktop Computer'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('server', 'Server'), ('other', 'Other')], default='other', help_text='Type of device', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('training', 'Training'), ('error', 'Error'), ('banned', 'Banned')], db_index=True, default='inactive', help_text='Current status of the client', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, help_text='Last time this client connected', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last known IP address', null=True)),
                ('capabilities', models.JSONField(default=dict, help_text='Device capabilities (CPU, GPU, RAM, etc.)')),
                ('total_training_rounds', models.IntegerField(default=0, help_text='Total number of training rounds participated in')),
                ('total_samples_contributed', models.IntegerField(default=0, help_text='Total training samples contributed')),
                ('average_training_time', models.FloatField(default=0.0, help_text='Average time per training round (seconds)')),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication', max_length=64, unique=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this device', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Federated Client',
                'verbose_name_plural': 'Federated Clients',
                'ordering': ['-last_seen', 'name'],
                'indexes': [models.Index(fields=['status', 'last_seen'], name='clients_cli_status_b583f4_idx'), models.Index(fields=['device_id'], name='clients_cli_device__cb00d4_idx')],
            },
        ),
    ]
