# Generated by Django 4.2.7 on 2025-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for authentication', max_length=64, null=True, unique=True),
        ),
    ]
