# Generated by Django 4.2.7 on 2025-11-06 13:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.IntegerField(db_index=True, help_text='Sequential round number', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the training round', max_length=20)),
                ('min_clients', models.IntegerField(default=2, help_text='Minimum number of clients required', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField(blank=True, help_text='When training started', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total duration in seconds', null=True)),
                ('config', models.JSONField(default=dict, help_text='Training configuration (learning rate, epochs, etc.)')),
                ('metrics', models.JSONField(default=dict, help_text='Aggregated metrics from all clients')),
                ('average_loss', models.FloatField(blank=True, help_text='Average loss across all clients', null=True)),
                ('average_accuracy', models.FloatField(blank=True, help_text='Average accuracy across all clients', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('participants', models.ManyToManyField(help_text='Clients participating in this round', related_name='training_rounds', to='clients.client')),
            ],
            options={
                'verbose_name': 'Training Round',
                'verbose_name_plural': 'Training Rounds',
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Training image file', upload_to='training_images/%Y/%m/%d/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (dimensions, format, etc.)')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this image has been validated')),
                ('validation_notes', models.TextField(blank=True, help_text='Notes from validation process')),
                ('times_used_in_training', models.IntegerField(default=0, help_text='Number of times used in training rounds')),
                ('client', models.ForeignKey(blank=True, help_text='Client device that uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='clients.client')),
                ('object_category', models.ForeignKey(help_text='Category this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_images', to='objects.objectcategory')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Image',
                'verbose_name_plural': 'Training Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(db_index=True, help_text="Version string (e.g., '1.0.0', 'v2-20231106')", max_length=50, unique=True)),
                ('model_file', models.FileField(help_text='Trained model file', upload_to='models/%Y/%m/')),
                ('model_size_mb', models.FloatField(blank=True, help_text='Model file size in MB', null=True)),
                ('accuracy', models.FloatField(help_text='Model accuracy on validation set', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('precision', models.FloatField(blank=True, help_text='Model precision', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recall', models.FloatField(blank=True, help_text='Model recall', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('f1_score', models.FloatField(blank=True, help_text='F1 score', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_production', models.BooleanField(db_index=True, default=False, help_text='Whether this is the production model')),
                ('deployed_at', models.DateTimeField(blank=True, help_text='When this model was deployed to production', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional model metadata')),
                ('notes', models.TextField(blank=True, help_text='Release notes or description')),
                ('training_round', models.OneToOneField(help_text='Training round that produced this model', on_delete=django.db.models.deletion.CASCADE, related_name='model_version', to='training.traininground')),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='traininground',
            index=models.Index(fields=['status', 'round_number'], name='training_tr_status_ea7305_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingimage',
            index=models.Index(fields=['object_category', 'is_validated'], name='training_tr_object__9abe4b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingimage',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='training_tr_uploade_fa292d_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['is_production', '-created_at'], name='training_mo_is_prod_1dc1d3_idx'),
        ),
    ]
