# Generated by Django 4.2.7 on 2025-11-06 20:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininground',
            name='min_clients',
        ),
        migrations.AddField(
            model_name='traininground',
            name='num_clients',
            field=models.IntegerField(default=2, help_text='Number of clients in this round', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='traininground',
            name='round_number',
            field=models.IntegerField(db_index=True, help_text='Sequential round number'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('model_name', models.CharField(default='mobilenet_v3_small', help_text='Name of the model architecture', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the training session', max_length=20)),
                ('num_rounds', models.IntegerField(default=10, help_text='Total number of planned rounds', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_round', models.IntegerField(default=0, help_text='Current round number')),
                ('config', models.JSONField(default=dict, help_text='Session configuration')),
                ('start_time', models.DateTimeField(blank=True, help_text='When session started', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When session completed', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='traininground',
            name='training_session',
            field=models.ForeignKey(blank=True, help_text='Parent training session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='training.trainingsession'),
        ),
    ]
