# Generated by Django 4.2.7 on 2025-11-06 13:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('training', '0001_initial'),
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image that was analyzed', upload_to='detections/%Y/%m/%d/')),
                ('confidence', models.FloatField(help_text='Confidence score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('bounding_box', models.JSONField(blank=True, help_text='Bounding box coordinates {x, y, width, height}', null=True)),
                ('inference_time_ms', models.FloatField(blank=True, help_text='Inference time in milliseconds', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='User feedback on detection accuracy', null=True)),
                ('feedback_notes', models.TextField(blank=True, help_text='User feedback or notes')),
                ('metadata', models.JSONField(default=dict, help_text='Additional detection metadata')),
                ('client', models.ForeignKey(blank=True, help_text='Client that performed the detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='clients.client')),
                ('detected_object', models.ForeignKey(blank=True, help_text='Detected object category (null if no detection)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='objects.objectcategory')),
                ('model_version', models.ForeignKey(help_text='Model version used for detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='training.modelversion')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['detected_object', 'confidence'], name='detection_d_detecte_4ce81b_idx'), models.Index(fields=['client', '-created_at'], name='detection_d_client__46c1bb_idx'), models.Index(fields=['user', '-created_at'], name='detection_d_user_id_4a911c_idx'), models.Index(fields=['-created_at'], name='detection_d_created_cc21d2_idx')],
            },
        ),
    ]
